# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Sb <- function(d, k) {
    .Call('coopbreed_Sb', PACKAGE = 'coopbreed', d, k)
}

mean_rcpp <- function(x) {
    .Call('coopbreed_mean_rcpp', PACKAGE = 'coopbreed', x)
}

coopbreed <- function(paths, n_gener, n_patches, MutStep, n_mates, n_off, par_c, par_k, modify) {
    .Call('coopbreed_coopbreed', PACKAGE = 'coopbreed', paths, n_gener, n_patches, MutStep, n_mates, n_off, par_c, par_k, modify)
}

coopbreed2 <- function(paths, n_gener, n_patches, MutStep, n_mates_vec, n_off_vec, par_c_vec, par_k_vec) {
    .Call('coopbreed_coopbreed2', PACKAGE = 'coopbreed', paths, n_gener, n_patches, MutStep, n_mates_vec, n_off_vec, par_c_vec, par_k_vec)
}

